fail_fast: false
repos:
- repo: local
  hooks:
    - id: docformatter
      name: docformatter
      entry: poetry run docformatter --in-place -r
      language: system
      types: [ file, python ]
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [ file, python ]
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [file, python]
    - id: pylint
      name: pylint
      entry: poetry run pylint
      language: system
      types: [ file, python ]